#!/bin/sh
#
# eswitchd  Mellanox Eswitch Daemon 
#
# chkconfig:   - 97 02
# description: Mellanox Eswitch Daemon
### END INIT INFO

. /etc/rc.d/init.d/functions

proj=eswitchd
prog=$proj
exec="/usr/bin/eswitchd"
config="/etc/$proj/eswitchd.conf"
pidfile="/var/run/$proj/$prog.pid"
logfile="/var/log/eswitchd/eswitchd.log"
plugin_config="/etc/quantum/plugins/mlnx/mlnx_conf.ini"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
   
    if [ "$OPENSTACK" == "yes" ];then
        if [ -f $plugin_config ];then
            daemon --pidfile $pidfile "$exec --config-file /etc/$proj/$proj.conf --config-file $plugin_config &>/dev/null & echo \$! > $pidfile"
        else
            echo $"Configured with OPENTACK=yes but can't find $plugin_config"
            failure $"Configured with OPENTACK=yes but can't find $plugin_config"
        fi
    else
        daemon --pidfile $pidfile "$exec --config-file /etc/$proj/$proj.conf &>/dev/null & echo \$! > $pidfile"
    fi
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval

}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    stop_lri
    return $retval
}

stop_lri() {
    pkill -9 -f '/usr/local/bin/lri*'
}
restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
